spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sauravchikurdekar/configuration_properties
          clone-on-start: true
          
management:
  security:
   enable: false         