server:
  port: 3333
 
spring:
   application:
        name:   API-GATEEAY
        
cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
          
routes:
  -id: one  
  url: lb://WELCOME-API
  predicate:
   -path=/welcome
          
-id: two
url: lb://GREET-API
predicate:
 -path=/greet
          